import importlib

class Pipeline:
    def __init__(self, df):
        self.df = df
        self.reports = []

    def report(self, result):
        """
        Function to add results to the report list
        """

        if isinstance(result, list):
            self.reports.extend(result)
        else:
            self.reports.append(result)

    def run(self, actions_config):
        """
        Run a sequence of actions defined in the validation.yml in config folder,
        and return all reports generated by the actions
        """
        for action_dict in actions_config:
            action_name, params = list(action_dict.items())[0]
            module = importlib.import_module(f"pipeline.actions.{action_name.lower()}")
            action_class = getattr(module, action_name)
            action_instance = action_class(params, self)
            action_instance.run()

        return self.reports